## scale models

center <- function(logWpara) {
  g <- apply(logWpara, c(2,3), FUN=`mean`)
  return(sweep(logWpara, c(2,3), g, FUN=`-`))
 }

##' Default scale model discussed in Nixon et al. Beyond Normalizations
##'
##' @param gamma TODO fix documentation
##' @return N x nsample matrix
##' @author Justin Silverman
default <- function(X, Y, logWpara) {
  gamma <- 0.5 # TODO provide functionality so this is no longer hard coded
  P <- nrow(X)
  nsample <- dim(logWpara)[3]
  logWperp <- -colMeans(logWpara, dims=1)

  tmp <- P*nsample
  Lambdaperp <- matrix(rnorm(tmp,0,gamma), P, nsample)
  logWperp <- logWperp + t(X)%*% Lambdaperp
  return(logWperp)
}


## scale models

#' Compute log-scale estimates of sample scale of a biological system (Wperp) 
#' 
#' The \code{GAMMA} function performs one of two calculations, depending on whether
#' \code{externalscale} is provided in \code{user_data}:
#'
#' \itemize{
#'   \item \strong{Case A (No external scale)}:
#'         If \code{externalscale} is \code{NULL}, the function assumes
#'         a "CLR" (centered log-ratio) normalization of the count matrix (Y). 
#'         It takes the existing relative abundance matrix with monte carlo draws
#'         \code{logWpara} array (dimensions: \code{[D, N, nsample]})
#'         from which a baseline offset is computed via \code{-colMeans(logWpara, dims = 1)}.
#'         Then, a user-specified design matrix \code{X} is used (required in \code{user_data["X"]})
#'         to multiply random draws from \code{N(0, gamma)}. 
#'         Optionally, you can perform a sensitivity analysis (varying \code{gamma})
#'         by calling \code{\link{GAMMA.sensitivity}}.
#'
#'   \item \strong{Case B (External scale)}:
#'         If \code{externalscale} is provided, \code{X} is ignored.
#'         The function then draws from \code{N(externalscale[i], gamma[i])} (or uses
#'         a scalar \code{gamma} for all elements) to reflect uncertainty 
#'         across all external scale measurements. In that scenario, you directly
#'         specify the means (\code{externalscale}) and standard deviations (\code{gamma})
#'         for each row, resulting in an \code{N}-by-\code{nsample} output.
#'         Likewise, you can perform a sensitivity analysis when you want to test 
#'         a range of uncertainty in the \code{externalscale} values by calling 
#'         \code{\link{GAMMA.sensitivityexternal}} with multiple \code{gamma} values.
#'
#' }
#'
#' In both cases, the function returns a matrix of the same dimension as the eventual
#' offset terms used in subsequent calculations—typically \code{[N, nsample]}.
#'
#' @param logWpara A three-dimensional array used to derive the baseline offset. Typically,
#'   its dimensions are \code{[D, N, nsample]}, with the third dimension
#'   representing Monte Carlo samples. This is not user supplied and is generated by calling aldex.lm()
#'
#' @param user_data A named list containing user-supplied data. Possible entries include:
#'   \describe{
#'     \item{\code{X}}{(matrix) The design matrix. Required if \code{externalscale} is \code{NULL}.}
#'     \item{\code{Y}}{(optional) Additional data, not explicitly used here by default, but may be used 
#'                     in custom analysis to estimate uncertainty from counts.}
#'     \item{\code{gamma}}{(numeric) The standard deviation(s) for random draws. Can be a single value
#'                         (replicated across all rows) or a vector of the same length as \code{externalscale}.
#'                         Defaults to 0.5 if \code{NULL}.}
#'     \item{\code{externalscale}}{(numeric) A vector providing the means for 
#'                                 external-scale (qPCR, Flow Cytometry, etc.) normal draws. 
#'                                 If supplied, \code{X} is ignored. If \code{NULL}, \code{X} is required.}
#'   }
#'
#' @details
#' This function also checks whether the final output appears to be in log2 format. If values
#' fall outside a typical range (\code{-15} to \code{30}), a warning is issued. If values exceed
#' \code{100}, it attempts an automatic conversion from natural log (\code{log(e)}) to \code{log2}.
#'
#' @return A numeric matrix of dimension \code{[N, nsample]}, where \code{N} is either
#' \code{ncol(X)} (if using the design matrix) or \code{length(externalscale)} (if using external scales).
#'
#' @author
#'   \strong{Primary Author:} Justin Silverman \cr
#'   \strong{Contributor:} Maxwell Konnaris \cr 
#'   \strong{Contributor:} Kyle McGovern
#'
#' @examples
#' # Example usage with no external scale:
#' logWpara <- array(rnorm(3 * 5 * 100), dim = c(3, 5, 100))
#' X <- matrix(rnorm(5 * 3), nrow = 5)
#' logWperp <- GAMMA.default(logWpara, list(X = X, gamma = 0.5))
#'
#' # Example usage with external scale (qPCR or Flow Cytometry):
#' externalscale <- c(1, 2, 3, 4, 5)
#' logWperp_ext <- GAMMA.external(logWpara, list(externalscale = externalscale, gamma = 0.2))
#'
#' # Suppose externalscale is a numeric vector, gamma contains SD from repeated measurements:
#' logWperp_ranged <- GAMMA.external(logWpara, list(externalscale = externalscale, gamma = c(0.1, 0.2, 0.15, 0.01, 0.05)))
#'
#' # Sensitivity analysis with varying gamma (No external scale):
#' gamma_values <- c(0.1, 0.5, 1.0)
#' sensitivity_results <- GAMMA.sensitivity(logWpara, X, gamma_values)
#'
#' # Sensitivity analysis with external scale and varying gamma:
#' sensitivity_ext_results <- GAMMA.sensitivityexternal(logWpara, externalscale, gamma_values)
#' 
#' @export
GAMMA <- function(logWpara, user_data = list()) {
  # user_data can contain:
  #   X             => (matrix) required if externalscale is NULL
  #   Y             => (not explicitly used here, but can be used to estimate uncertainty from counts.)
  #   gamma         => (numeric) a single value or vector
  #   externalscale => (numeric) vector of means for normal draws; if supplied, X is ignored.
  
  X             <- user_data[["X"]]
  Y             <- user_data[["Y"]]  # included if needed downstream
  gamma         <- user_data[["gamma"]]
  externalscale <- user_data[["externalscale"]]
  
  # Default gamma if not provided
  if (is.null(gamma)) gamma <- 0.5
  
  # Number of Monte Carlo samples 
  nsample  <- dim(logWpara)[3]
  
  # ------------------------------
  # Case B: If externalscale is provided, ignore X
  # ------------------------------
  if (!is.null(externalscale)) {
    P <- length(externalscale)
    
    # If gamma is scalar, replicate to length P
    if (length(gamma) == 1) {
      gamma_vec <- rep(gamma, P)
    } else {
      gamma_vec <- gamma
      if (length(gamma_vec) != P) {
        stop("Length of 'gamma' does not match length of 'externalscale'.")
      }
    }
    
    # Generate P x nsample matrix
    logWperp <- t(sapply(seq_len(P), function(i) {
      rnorm(nsample, mean = externalscale[i], sd = gamma_vec[i])
    }))
    
    # Quick dimension check
    if (!all(dim(logWperp) == c(P, nsample))) {
      stop("Dimension mismatch: final logWperp is not [N, nsample].")
    }
    
  } else {
    # ------------------------------
    # Case A: No externalscale => require X
    # ------------------------------
    if (is.null(X)) {
      stop("If 'externalscale' is NULL, you must provide 'X' in user_data.")
    }
    
    # P = number of rows in X
    P <- nrow(X)
    
    # Baseline offset from logWpara
    logWperp <- -colMeans(logWpara, dims = 1)
    
    # Random draws from N(0, gamma)
    Lambdaperp <- matrix(
      rnorm(P * nsample, mean = 0, sd = gamma),
      nrow = P, ncol = nsample
    )
    
    # Dimension check for the matrix addition t(X) %*% Lambdaperp
    # We need logWperp shaped [ncol(X), nsample]
    if (!all(dim(logWperp) == c(ncol(X), nsample))) {
      stop("Dimension mismatch: for no-external-scale mode, 
           need logWperp shaped [ncol(X), nsample].")
    }
    
    logWperp <- logWperp + t(X) %*% Lambdaperp
  }
  
  # ------------------------------
  # Basic check if logWperp is in a plausible log2 range
  # ------------------------------
  min_val <- min(logWperp, na.rm = TRUE)
  max_val <- max(logWperp, na.rm = TRUE)
  
  if (min_val < -15 || max_val > 30) {
    warning("Values in logWperp seem outside typical log2 range (-15 to 30). ",
            "Check data format or consider adjusting your assumptions.")
  }
  
  # If extremely large values, assume it's in log(e) and auto-convert
  if (max_val > 100) {
    warning("Very large values detected; auto-converting from log(e) to log2.")
    logWperp <- log2(exp(logWperp))
  }
  
  return(logWperp)
}


#' Default GAMMA Calculation (No External Scale Measurements)
#'
#' This convenience wrapper calls \code{\link{GAMMA}} assuming you have
#' a design matrix \code{X} and a single (or vector) \code{gamma},
#' with \code{externalscale = NULL}.
#'
#' @param logWpara A three-dimensional array (see \code{\link{GAMMA}}).
#' @param X A design matrix (see details in \code{\link{GAMMA}}).
#' @param gamma Standard deviation(s) for the normal draws; defaults to 0.5.
#'
#' @return A matrix of dimension \code{[ncol(X), nsample]} matching the output of \code{\link{GAMMA}}.
#' @seealso \code{\link{GAMMA}}
#' @export
GAMMA.default <- function(logWpara, X, gamma = 0.5) {
  user_data <- list(X = X, gamma = gamma, externalscale = NULL)
  GAMMA(logWpara, user_data)
}


#' External Scale GAMMA Calculation
#'
#' This wrapper calls \code{\link{GAMMA}} using user-supplied external scales
#' (e.g., from qPCR or flow data). The \code{externalscale} vector provides
#' the means of the normal draws, and \code{gamma} provides the standard
#' deviations (can be a single value or match \code{length(externalscale})).
#'
#' @param logWpara A three-dimensional array (see \code{\link{GAMMA}}).This is not user supplied and is generated by calling aldex.lm()
#' @param externalscale A numeric vector of means for normal draws.
#' @param gamma Standard deviation(s) for the normal draws; defaults to 0.5.
#'
#' @return A matrix of dimension \code{[length(externalscale), nsample]}.
#' @seealso \code{\link{GAMMA}}
#' @export
GAMMA.external <- function(logWpara, externalscale, gamma = 0.5) {
  user_data <- list(externalscale = externalscale, gamma = gamma)
  GAMMA(logWpara, user_data)
}


#' Sensitivity Analysis for Multiple Gamma Values (No External Scale)
#'
#' This wrapper calls \code{\link{default_GAMMA}} iteratively over
#' a set of \code{gamma_values}, returning a list of results for each gamma.
#'
#' @param logWpara A three-dimensional array (see \code{\link{GAMMA}}). This is not user supplied and is generated by calling aldex.lm()
#' @param X A design matrix used in \code{\link{default_GAMMA}}.
#' @param gamma_values A numeric vector of \code{gamma} values to test.
#'
#' @return A list of matrices; each element is the result of one call to
#'         \code{\link{default_GAMMA}}.
#' @seealso \code{\link{default_GAMMA}}, \code{\link{GAMMA}}
#' @export
#'
#' @examples
#' # Suppose we have logWpara, a design matrix X, and multiple gamma values:
#' # results <- GAMMA.sensitivity(logWpara, X, c(0.1, 0.5, 1.0))
#' # str(results)  # Each list element is a matrix for the corresponding gamma
GAMMA.sensitivity <- function(logWpara, X, gamma_values) {
  lapply(gamma_values, function(g) {
    GAMMA.default(logWpara, X, gamma = g)
  })
}


#' Sensitivity Analysis for Multiple Gamma Values (With External Scale)
#'
#' This wrapper calls \code{\link{external_GAMMA}} iteratively over
#' a set of \code{gamma_values}, returning a list of results for each gamma.
#'
#' Use this when external scale measurements exist but you need to explore
#' uncertainty (i.e., you do not know the precise measurement SD).
#'
#' @param logWpara A three-dimensional array (see \code{\link{GAMMA}}). This is not user supplied and is generated by calling aldex.lm()
#' @param externalscale A numeric vector of means for normal draws (see \code{\link{external_GAMMA}}).
#' @param gamma_values A numeric vector of \code{gamma} values to test.
#'
#' @return A list of matrices; each element is the result of one call to
#'         \code{\link{external_GAMMA}}.
#' @seealso \code{\link{external_GAMMA}}, \code{\link{GAMMA}}
#' @export
#'
#' @examples
#' # Suppose externalscale is c(1, 2, 3), and we want to test multiple gamma values:
#' # results_ext <- GAMMA.sensitivityexternal(logWpara, c(1,2,3), c(0.1, 0.5, 1.0))
#' # str(results_ext)  # Each list element is a matrix for the corresponding gamma
GAMMA.sensitivityexternal <- function(logWpara, externalscale, gamma_values) {
  lapply(gamma_values, function(g) {
    GAMMA.external(logWpara, externalscale = externalscale, gamma = g)
  })
}



